parameters:

services:
    rbs_erp.core.configure_menu_listener:
        class: Rbs\Bundle\CoreBundle\EventListener\ConfigureMenuListener
        arguments: [@service_container]
        tags:
          - { name: kernel.event_listener, event: core_bundle.menu_main, method: onMenuConfigureMain, priority: 999 }


    rbs_erp.core.datatable.category:
        class: Rbs\Bundle\CoreBundle\Datatables\CategoryDatatable
        tags:
            - { name: sg.datatable.view }

    rbs_erp.core.datatable.area:
            class: Rbs\Bundle\CoreBundle\Datatables\AreaDatatable
            tags:
                - { name: sg.datatable.view }